[DPM-128] action traces
DaoCasino/game-contract-sdk pull request #31
Opened 2020-04-30 09:06 UTC by sadsnake42

Store for each transaction all events and clean it before next transaction.

2020-04-30 14:08 UTC, algys requested changes

2020-04-30 14:08 UTC, algys commented on tester/include/game_tester/contracts.hpp.in
> +    struct events_struct {
it's not related to "contracts" struct, so shouldn't be under it

2020-04-30 14:08 UTC, algys commented on tester/include/game_tester/contracts.hpp.in
>              static std::vector<char>    abi() { return read_abi("${PLATFORM_CONTRACTS_PATH}/platform/platform.abi"); }
better to use new `abi_path` in `abi` method, like: `.. abi() { return read_abi(abi_path()); }`

2020-04-30 14:08 UTC, algys commented on tester/include/game_tester/game_tester.hpp
> +enum events_id {
we prefer scoped enums

2020-04-30 14:08 UTC, algys commented on tester/include/game_tester/game_tester.hpp
> +        abi_ser.set_abi(events_abi, abi_serializer_max_time);
It's better to move things like that to another function like init_abis and call once from tester constructor, else that stuff invokes for each trx. And same with `handle_action_data`.

2020-04-30 14:08 UTC, algys commented on tester/include/game_tester/game_tester.hpp
> +                if (action_trace.receiver != "events")
also add filter by action name, allow only send action

2020-04-30 14:10 UTC, algys commented
How about this push_action: https://github.com/DaoCasino/game-contract-sdk/blob/dpm-128-action-traces/tester/include/game_tester/game_tester.hpp#L159 ? I guess, it should use our push_action to register action traces.

2020-04-30 14:10 UTC, algys commented
Also need to add minimal usage example in tests.

2020-05-06 06:48 UTC, sadsnake42 commented
Question about [`return base_tester::push_action(std::move(act), actor);`](https://github.com/DaoCasino/game-contract-sdk/blob/dpm-128-action-traces/tester/include/game_tester/game_tester.hpp#L181). I can't find any other functions which return `transaction_ptr`. I thought all `push_` functions use out [`push_action`](https://github.com/DaoCasino/game-contract-sdk/blob/4864061ffc14a60fe8782e648eebd162c92fc4ef/tester/include/game_tester/game_tester.hpp#L192). This is't true?

2020-05-06 07:21 UTC, sadsnake42 commented
Test added

2020-05-07 13:45 UTC, algys approved these changes

2020-05-08 05:18 UTC, merged